message-error:
  country: "BR"
  language: "pt-br"

spring:
  datasource:
    url: jdbc:h2:mem:customer_db
    driver-class-name: org.h2.Driver
    username: sa
    password: sa123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        hbm2ddl:
          import_files: data/insert_customer.sql
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false